server:
  port: 8888

spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
  datasource:
    url: jdbc:mysql://192.168.181.128:3306/im?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    hikari:
      minimum-idle: 20
      maximum-pool-size: 50
      max-lifetime: 300000
      connection-timeout: 30000

login:
  key: ydy-im