server:
  port: 9000

spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      max-lifetime: 300000
      connection-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.80.147
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: 300
        max-idle: 10
        min-idle: 0
    timeout: 30000

login:
  key: ydy-im

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml #指定扫描Mapper.xml文件规则
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

